version: '3.7'
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    container_name: cakes-shop-db
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
